<?php

namespace AppBundle\Repository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySortingAndPagination($sortBy, $sortOrder, $page, $limit)
    {
       $queryBuilder = $this->createQueryBuilder('h')
           ->orderBy('h.' . $sortBy, $sortOrder)
           ->setFirstResult(($page - 1) * $limit)
           ->setMaxResults($limit);

       return $queryBuilder->getQuery()->getResult();
    }
}
