version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    environment:
    PHP_FPM_REQUEST_TIMEOUT: 300s
    ports:
      - "9000:9000"  # Zmieniamy port na 9001
    volumes:
      - ./symfony:/var/www/project

  mysql:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8889:80  # Zmieniamy port na 8889
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
